name: ğŸ° Release Unstable

on:
    push:
        tags:
            - 'v*.*.*-alpha.*'
            - 'v*.*.*-beta.*'
            - 'v*.*.*-rc.*'

permissions:
    contents: read

jobs:
    release-unstable:
        if: github.repository == 'dream-num/univer'
        runs-on: ubuntu-latest

        outputs:
            release_type: ${{ steps.release-type.outputs.release_type }}

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Install pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 8
                  run_install: false

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  registry-url: https://registry.npmjs.org

            - name: ğŸšš Get release type
              id: release-type
              run: |
                  if [[ ${{ github.ref_name }} =~ -(rc|beta|alpha)\. ]]; then
                      extracted_type="${BASH_REMATCH[1]}"
                      echo "release_type=$extracted_type" >> $GITHUB_OUTPUT
                  fi

            - name: ğŸšš Install dependencies
              run: pnpm install

            - name: ğŸ“¦ Build
              run: pnpm run build

            - name: ğŸ™ Publish (alpha)
              if: ${{ steps.release-type.outputs.release_type == 'alpha' }}
              run: pnpm publish --access public --tag ${{ steps.release-type.outputs.release_type }} -r
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: ğŸ™ Publish (beta, rc)
              if: ${{ steps.release-type.outputs.release_type == 'beta' || steps.release-type.outputs.release_type == 'rc' }}
              run: pnpm publish --access public -r
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    build-demo:
        runs-on: ubuntu-latest
        needs: [release-unstable]

        outputs:
            preview-url: ${{ steps.vercel-demo.outputs.preview-url }}

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: ./.github/actions/setup-node

            #  ================= Deploy Demo =================
            - name: ğŸ“¦ Build demo
              run: pnpm run build:demo

            - name: Copy demo to workspace
              run: |
                  mkdir .workspace
                  cp -r ./examples/local/* .workspace

            - name: ğŸš€ Deploy to Vercel (demo)
              uses: amondnet/vercel-action@v25
              id: vercel-demo
              with:
                  vercel-token: ${{ secrets.VERCEL_TOKEN }}
                  vercel-org-id: ${{ secrets.ORG_ID}}
                  vercel-project-id: ${{ secrets.PROJECT_ID}}

    build-storybook:
        runs-on: ubuntu-latest
        needs: [release-unstable]

        outputs:
            preview-url: ${{ steps.vercel-storybook.outputs.preview-url }}

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: ./.github/actions/setup-node

            # ================= Deploy Storybook =================
            - name: ğŸ“¦ Build storybook
              run: pnpm run build:storybook

            - name: ğŸš€ Deploy to Vercel (storybook)
              uses: amondnet/vercel-action@v25
              id: vercel-storybook
              with:
                  vercel-token: ${{ secrets.VERCEL_TOKEN }}
                  vercel-org-id: ${{ secrets.ORG_ID}}
                  vercel-project-id: ${{ secrets.PROJECT_ID_STORYBOOK}}
                  vercel-args: --prod

    notify:
        needs: [release-unstable, build-demo, build-storybook]
        runs-on: ubuntu-latest
        if: ${{ always() }}

        steps:
            # ================= Notify Discord =================
            - name: ğŸ‘¾ Discord Notification
              uses: sarisia/actions-status-discord@v1
              if: ${{ success() }}
              with:
                  webhook: ${{ secrets.DISCORD_WEBHOOK }}?thread_id=${{ secrets.DISCORD_CI_UNSTABLE_RELEASE }}
                  status: ${{ job.status }}
                  description: |
                      ğŸ‰ Unstable release: Successful

                      ğŸ‰ ğŸ‰ ğŸ‰ ğŸ‰ ğŸ‰ ğŸ‰ ğŸ‰ ğŸ‰ ğŸ‰
                      Release version: ${{ github.ref_name }}

                      **[View Deployment]**
                      - [ğŸ“‘ Examples](${{ needs.build-demo.outputs.preview-url }}/)

                      **[View Docs]**
                      - [ğŸ“š Storybook](${{ needs.build-storybook.outputs.preview-url }}/)
                      ğŸ‰ ğŸ‰ ğŸ‰ ğŸ‰ ğŸ‰ ğŸ‰ ğŸ‰ ğŸ‰ ğŸ‰

                      Have a good dream! ğŸŒ™
                  nofail: false
                  nodetail: false
                  nocontext: false
                  noprefix: true
                  color: 0x00b894
                  username: Unstable Release

            - name: ğŸ‘¾ Discord Notification
              uses: sarisia/actions-status-discord@v1
              if: ${{ failure() }}
              with:
                  webhook: ${{ secrets.DISCORD_WEBHOOK }}?thread_id=${{ secrets.DISCORD_CI_UNSTABLE_RELEASE }}
                  status: ${{ job.status }}
                  description: |
                      ğŸ’¥ Ustable release: Unsuccessful ğŸ’©

                      ğŸ‘¿ ğŸ‘¿ ğŸ‘¿ ğŸ‘¿ ğŸ‘¿ ğŸ‘¿ ğŸ‘¿ ğŸ‘¿ ğŸ‘¿
                      Failed version: ${{ github.ref_name }}
                      ğŸ‘¿ ğŸ‘¿ ğŸ‘¿ ğŸ‘¿ ğŸ‘¿ ğŸ‘¿ ğŸ‘¿ ğŸ‘¿ ğŸ‘¿

                      Oops! Something went wrong. ğŸ˜­
                  nofail: false
                  nodetail: false
                  nocontext: false
                  noprefix: true
                  color: 0xd63031
                  username: Unstable Release
