name: ğŸ¥· Release Nightly

on:
    schedule:
        - cron: '30 1 * * *'

permissions:
    contents: read

jobs:
    release-nightly:
        if: github.repository == 'dream-num/univer'
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 8
                  run_install: false

            - name: Get pnpm store directory
              shell: bash
              run: |
                  echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

            - name: Setup pnpm cache
              uses: actions/cache@v3
              with:
                  path: ${{ env.STORE_PATH }}
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-

            - name: Get package version(version + date)
              id: nightly-version
              run: |
                  echo "::set-output name=version::$(node -p "require('./package.json').version")-nightly-$(date +%Y%m%d%H%M)"

            # - name: Create tag
            #   uses: actions/github-script@v5
            #   with:
            #       github-token: ${{ secrets.GITHUB_TOKEN }}
            #       script: |
            #           github.rest.git.createRef({
            #             owner: context.repo.owner,
            #             repo: context.repo.repo,
            #             ref: 'refs/tags/${{ steps.nightly-version.outputs.version }}',
            #             sha: context.sha
            #           })

            - name: Set all monorepo's package version
              run: |
                  for package in $(ls packages); do
                      node -e "const fs = require('fs'); const package = JSON.parse(fs.readFileSync('./packages/$package/package.json')); package.version = '${{ steps.nightly-version.outputs.version }}'; fs.writeFileSync('./packages/$package/package.json', JSON.stringify(package, null, 4));"
                  done

            - name: Install dependencies
              run: pnpm install

            - name: Build
              run: pnpm run build

            - name: Set publishing config
              run: pnpm config set '${NODE_REGISTRY}:_authToken' "${NODE_AUTH_TOKEN}"
              env:
                  NODE_REGISTRY: ${{ secrets.VERDACCIO_URL }}
                  NODE_AUTH_TOKEN: ${{ secrets.VERDACCIO_TOKEN }}
 
            - name: Publish
              run: pnpm publish --access public --tag nightly -r

            # ================= Notify Discord =================
            - name: ğŸ‘¾ Discord Notification
              uses: sarisia/actions-status-discord@v1
              if: ${{ success() }}
              with:
                    webhook: ${{ secrets.DISCORD_WEBHOOK }}
                    status: ${{ job.status }}
                    description: |
                        ğŸŒ Nightly release: Successful

                        ğŸ‰ ğŸ‰ ğŸ‰ ğŸ‰ ğŸ‰ ğŸ‰ ğŸ‰ ğŸ‰ ğŸ‰
                        Release version: ${{ steps.nightly-version.outputs.version }}
                        ğŸ‰ ğŸ‰ ğŸ‰ ğŸ‰ ğŸ‰ ğŸ‰ ğŸ‰ ğŸ‰ ğŸ‰

                        Have a good dream! ğŸŒ™
                    nofail: false
                    nodetail: false
                    nocontext: false
                    noprefix: true
                    color: 0x00b894
                    username: Nightly Release

            - name: ğŸ‘¾ Discord Notification
              uses: sarisia/actions-status-discord@v1
              if: ${{ failure() }}
              with:
                    webhook: ${{ secrets.DISCORD_WEBHOOK }}
                    status: ${{ job.status }}
                    description: |
                        ğŸŒš Nightly release: Unsuccessful ğŸ’©

                        ğŸ‘¿ ğŸ‘¿ ğŸ‘¿ ğŸ‘¿ ğŸ‘¿ ğŸ‘¿ ğŸ‘¿ ğŸ‘¿ ğŸ‘¿
                        Failed version: ${{ steps.nightly-version.outputs.version }}
                        ğŸ‘¿ ğŸ‘¿ ğŸ‘¿ ğŸ‘¿ ğŸ‘¿ ğŸ‘¿ ğŸ‘¿ ğŸ‘¿ ğŸ‘¿

                        Don't worry, tomorrow will be better! ğŸŒ
                    nofail: false
                    nodetail: false
                    nocontext: false
                    noprefix: true
                    color: 0xd63031
                    username: Nightly Release
